### PR TITLE
update kafkaRetryJobService to get metadata once.

### LINKED ISSUE #16: Get Metadata once instead of twice
In our current implementation, we are retrieving Metadata from the cluster twice: once in the [GetClusterTopics function](https://github.com/Trendyol/kafka-retry-job/blob/main/src/Services/Implementations/KafkaRetryJobService.cs#L114) function and again in the [GetTopicMetadata](https://github.com/Trendyol/kafka-retry-job/blob/main/src/Services/Implementations/KafkaRetryJobService.cs#L114) function. 

We could streamline this process to improve performance by retrieving the Metadata only once and reusing it as needed.

### PR DESCRIPTION
**Pull request by halilkocaoz**
I tried to resolve #16.

### CODE REVIEW

**Comment by halilkocaoz** [comment]
Greetings @MehmetFiratKomurcu, did you get a chance to look into this? If there's something you think is wrong, I can try to handle it.

**Comment by MehmetFiratKomurcu** [comment]
Hi Halil, I am sorry to late response, I will try to look github notifications asap from now. Thank you for your contribution. Can you upgrade the version from 1.8.0 to 1.9.0 in publish.yml file?

**Review by MehmetFiratKomurcu — COMMENTED** [review]
Hi Halil, I am sorry to late response, I will try to look github notifications asap from now. Thank you for your contribution. Can you upgrade the version from 1.8.0 to 1.9.0 in publish.yml and .gitlab-ci.yml files?

**Comment by halilkocaoz** [comment]
> Hi Halil, I am sorry to late response, I will try to look github notifications asap from now. Thank you for your contribution. Can you upgrade the version from 1.8.0 to 1.9.0 in publish.yml and .gitlab-ci.yml files?

It's not problem, also I thank you too.
Updated the version.

**Review by MehmetFiratKomurcu — APPROVED** [review]
thank you <3

**Pull request merged**
